version: "3.8"
services:
  app:
    container_name: "cmcontainer"
    image: "ecommerce-api"
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - smtp4dev

  mysqldb:
    container_name: "mysqlcontainer"
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "girogiro"
      MYSQL_DATABASE: "ecommerce"

  smtp4dev:
    container_name: "smtpcontainer"
    image: "rnwood/smtp4dev:latest"
    ports:
      - "3000:80"
      - "25:25"
